### ISSUE TITLE
ImportError: cannot import name 'cython_nms' from 'maskrcnn_benchmark.layers.cython_nms'

### ISSUE THREAD

**Issue by Lxy811** [jkli1998/T-CAR#1]
Can you help me see how to solve this problem?

**Comment by jkli1998** [comment]
Thanks for your attention.
We have checked the uploaded files and found that two locally compiled files (e.g. maskrcnn_benchmark/layers/cython_ms/cython_ms. cpython-37m-x86_64 Linux gnu. so) were mistakenly uploaded to repo. We have now deleted these files. You can clone this repo again and compile it. 
If you encounter any new problems, please contact me and I am happy to provide assistance.

**Comment by Lxy811** [comment]
> Thanks for your attention. We have checked the uploaded files and found that two locally compiled files (e.g. maskrcnn_benchmark/layers/cython_ms/cython_ms. cpython-37m-x86_64 Linux gnu. so) were mistakenly uploaded to repo. We have now deleted these files. You can clone this repo again and compile it. If you encounter any new problems, please contact me and I am happy to provide assistance.

Thank you
