### ISSUE TITLE
ImportError: cannot import name 'container_abcs'

### ISSUE THREAD

**Issue by Lxy811** [jkli1998/T-CAR#2]
from torch._six import container_abcs ImportError: cannot import name 'container_abcs'
Can you help me see how to solve this problem?Is it because of the torch version?

**Comment by jkli1998** [comment]
Yes, StackOverflow shows that runs ` from torch._six import container_abcs` at the pytorch greater than 1.9 will report an error, the correct code is to use 'import collections.abc as container_abcs'. 
Can you tell me which line of code in this repository runs the 'from torch._six import container_abcs'?

**Comment by Lxy811** [comment]
> Yes, StackOverflow shows that runs ` from torch._six import container_abcs` at the pytorch greater than 1.9 will report an error, the correct code is to use 'import collections.abc as container_abcs'. Can you tell me which line of code in this repository runs the 'from torch._six import container_abcs'?
![Snipaste_2024-02-28_22-15-33](https://github.com/jkli1998/T-CAR/assets/85209124/c6c178a5-23e2-4f47-af90-2c94ef20a6f3)

**Comment by jkli1998** [comment]
There is nothing wrong with this code.
I suspect the problem may be a conflict between your installed versions of ‘apex’ and ‘pytorch’.

**Comment by Lxy811** [comment]
> There is nothing wrong with this code. I suspect the problem may be a conflict between your installed versions of ‘apex’ and ‘pytorch’.

Ok, I'll have another look
