### ISSUE TITLE
BACKBONE to replace the VGG16 network

### ISSUE THREAD

**Issue by Lxy811** [jkli1998/T-CAR#3]
I want to ask, in the table1 experiment, how did the code implement BACKBONE into VGG16 network?
Should I replace the CONV_BODY attribute in the yaml file and retrain?

**Comment by Lxy811** [comment]
One more question: How did you get the file zeroshot_triplet_new.pytorch

**Comment by jkli1998** [comment]
> I want to ask, in the table1 experiment, how did the code implement BACKBONE into VGG16 network? Should I replace the CONV_BODY attribute in the yaml file and retrain?

We reimplement our method with VGG backbone based on https://github.com/bknyaz/sgg and https://github.com/rowanz/neural-motifs.

**Comment by jkli1998** [comment]
> One more question: How did you get the file zeroshot_triplet_new.pytorch

You can check this file: https://github.com/jkli1998/T-CAR/blob/main/zs_check.ipynb

**Comment by Lxy811** [comment]
> > One more question: How did you get the file zeroshot_triplet_new.pytorch
> 
> You can check this file: https://github.com/jkli1998/T-CAR/blob/main/zs_check.ipynb

Thank you very much

**Comment by Lxy811** [comment]
I would like to ask how to generate this file zeroshot_triplet_new.pytorch

**Comment by jkli1998** [comment]
> I would like to ask how to generate this file zeroshot_triplet_new.pytorch

zeroshot_triplet_new.pytorch contains triplets that appear in the test set but not in the training set. It is the 'zs_set' in the zs_check.ipynb file. You can generate it using torch.save(torch.tensor(zs_set), 'zeroshot_triplet_new.pytorch').

**Comment by Lxy811** [comment]
Hello, I would like to ask how the visualized diagrams and scene diagrams in the paper were obtained

> > I would like to ask how to generate this file zeroshot_triplet_new.pytorch
> 
> zeroshot_triplet_new.pytorch contains triplets that appear in the test set but not in the training set. It is the 'zs_set' in the zs_check.ipynb file. You can generate it using torch.save(torch.tensor(zs_set), 'zeroshot_triplet_new.pytorch').

thank you

**Comment by Lxy811** [comment]
Hello, I would like to ask how the visualized diagrams and scene diagrams in the paper were obtained

**Comment by Lxy811** [comment]
> > I would like to ask how to generate this file zeroshot_triplet_new.pytorch
> 
> zeroshot_triplet_new.pytorch contains triplets that appear in the test set but not in the training set. It is the 'zs_set' in the zs_check.ipynb file. You can generate it using torch.save(torch.tensor(zs_set), 'zeroshot_triplet_new.pytorch').

I would like to ask how to generate this file zeroshot_triplet.pytorch?

**Comment by jkli1998** [comment]
> > > I would like to ask how to generate this file zeroshot_triplet_new.pytorch
> > 
> > 
> > zeroshot_triplet_new.pytorch contains triplets that appear in the test set but not in the training set. It is the 'zs_set' in the zs_check.ipynb file. You can generate it using torch.save(torch.tensor(zs_set), 'zeroshot_triplet_new.pytorch').
> 
> I would like to ask how to generate this file zeroshot_triplet.pytorch?

The original file 'zeroshot_triplet.pytorch' is copied directly from this repo `https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/master/maskrcnn_benchmark/data/datasets/evaluation/vg/zeroshot_triplet.pytorch`.

**Comment by Lxy811** [comment]
> > > > I would like to ask how to generate this file zeroshot_triplet_new.pytorch
> > > 
> > > 
> > > zeroshot_triplet_new.pytorch contains triplets that appear in the test set but not in the training set. It is the 'zs_set' in the zs_check.ipynb file. You can generate it using torch.save(torch.tensor(zs_set), 'zeroshot_triplet_new.pytorch').
> > 
> > 
> > I would like to ask how to generate this file zeroshot_triplet.pytorch?
> 
> The original file 'zeroshot_triplet.pytorch' is copied directly from this repo `https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/master/maskrcnn_benchmark/data/datasets/evaluation/vg/zeroshot_triplet.pytorch`.

ok,thank you

**Comment by Lxy811** [comment]
How is the result of T-CAR when B is VGG-16 implemented in the paper? Is the downloaded vg-faster-rcnn.tar used as the pre-trained object detector? Or code that implements T-CAR models on the neural-motifs framework?
![Uploading Snipaste_2024-03-06_13-28-04.png…]()

**Comment by Lxy811** [comment]
![微信截图_20240306133018](https://github.com/jkli1998/T-CAR/assets/85209124/a732948d-3c45-4adf-9361-0cf3c45337a9)
How is the result of T-CAR when B is VGG-16 implemented in the paper? Is the downloaded vg-faster-rcnn.tar used as the pre-trained object detector? Or code that implements T-CAR models on the neural-motifs framework?

**Comment by jkli1998** [comment]
> ![微信截图_20240306133018](https://private-user-images.githubusercontent.com/85209124/310372730-a732948d-3c45-4adf-9361-0cf3c45337a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDYwNDAsIm5iZiI6MTcwOTcwNTc0MCwicGF0aCI6Ii84NTIwOTEyNC8zMTAzNzI3MzAtYTczMjk0OGQtM2M0NS00YWRmLTkzNjEtMGNmM2M0NTMzN2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA2MTU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YzBhNDFmMDM4NGMyOWY3MWRiZWM4YjRjOTNkY2I5ZjQxNjI1MmE1MjI3NGMxNGMxYjBlZjVkM2M1YmUwNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9hBaFyRFoeIGyVcx3Waer1xhb3Fygck9rWNlxxC8e_M) How is the result of T-CAR when B is VGG-16 implemented in the paper? Is the downloaded vg-faster-rcnn.tar used as the pre-trained object detector? Or code that implements T-CAR models on the neural-motifs framework?

We implement our approach with VGG-16 backbone based on neural-motifs framework. Since this part of our code is mess and unorganized, we only release our code based on Scene-Graph-Benchmark. You can integrate the code of this repo into neural-motifs framework to reproduce the corresponding results.

**Comment by Lxy811** [comment]
> > ![微信截图_20240306133018](https://private-user-images.githubusercontent.com/85209124/310372730-a732948d-3c45-4adf-9361-0cf3c45337a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDYwNDAsIm5iZiI6MTcwOTcwNTc0MCwicGF0aCI6Ii84NTIwOTEyNC8zMTAzNzI3MzAtYTczMjk0OGQtM2M0NS00YWRmLTkzNjEtMGNmM2M0NTMzN2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA2MTU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YzBhNDFmMDM4NGMyOWY3MWRiZWM4YjRjOTNkY2I5ZjQxNjI1MmE1MjI3NGMxNGMxYjBlZjVkM2M1YmUwNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9hBaFyRFoeIGyVcx3Waer1xhb3Fygck9rWNlxxC8e_M) How is the result of T-CAR when B is VGG-16 implemented in the paper? Is the downloaded vg-faster-rcnn.tar used as the pre-trained object detector? Or code that implements T-CAR models on the neural-motifs framework?
> 
> We implement our approach with VGG-16 backbone based on neural-motifs framework. Since this part of our code is mess and unorganized, we only release our code based on Scene-Graph-Benchmark. You can integrate the code of this repo into neural-motifs framework to reproduce the corresponding results.

Thank you very much

**Comment by Lxy811** [comment]
Sorry to bother you again, but I also want to ask backbone B whether the experimental results of multiple methods for ResNeXt-101-FPN are based on this t-car code
![微信截图_20240306160129](https://github.com/jkli1998/T-CAR/assets/85209124/c68fc843-1df4-40aa-af81-7234ac484fbc)

**Comment by jkli1998** [comment]
> Sorry to bother you again, but I also want to ask backbone B whether the experimental results of multiple methods for ResNeXt-101-FPN are based on this t-car code ![微信截图_20240306160129](https://private-user-images.githubusercontent.com/85209124/310426428-c68fc843-1df4-40aa-af81-7234ac484fbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Nzk4OTcsIm5iZiI6MTcwOTc3OTU5NywicGF0aCI6Ii84NTIwOTEyNC8zMTA0MjY0MjgtYzY4ZmM4NDMtMWRmNC00MGFhLWFmODEtNzIzNGFjNDg0ZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAyNDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZTRlNGMxMmZhYTBhYzQzYWJmMGMxNTNkZTY3MTMzNDQwZmY5ZjM2MDM5YTE3ZjAyNzQzOGI5MGQyMzJiY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j_hgraWi4Eu_XPRF2oRZLitaRxmoXRcm-zk6JVPQgZA)

Yes, we infer all of these baseline methods based on our generated `zeroshot_triplet_new.pytorch` for fair comparision.

**Comment by Lxy811** [comment]
> > Sorry to bother you again, but I also want to ask backbone B whether the experimental results of multiple methods for ResNeXt-101-FPN are based on this t-car code ![微信截图_20240306160129](https://private-user-images.githubusercontent.com/85209124/310426428-c68fc843-1df4-40aa-af81-7234ac484fbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Nzk4OTcsIm5iZiI6MTcwOTc3OTU5NywicGF0aCI6Ii84NTIwOTEyNC8zMTA0MjY0MjgtYzY4ZmM4NDMtMWRmNC00MGFhLWFmODEtNzIzNGFjNDg0ZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAyNDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZTRlNGMxMmZhYTBhYzQzYWJmMGMxNTNkZTY3MTMzNDQwZmY5ZjM2MDM5YTE3ZjAyNzQzOGI5MGQyMzJiY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j_hgraWi4Eu_XPRF2oRZLitaRxmoXRcm-zk6JVPQgZA)
> 
> Yes, we infer all of these baseline methods based on our generated `zeroshot_triplet_new.pytorch` for fair comparision.

![31313](https://github.com/jkli1998/T-CAR/assets/85209124/d79e5188-ad67-46c6-a2e6-b911168d78fa)
Hello, the method implementation of the red line part in the figure is not in this link code

**Comment by jkli1998** [comment]
> > > Sorry to bother you again, but I also want to ask backbone B whether the experimental results of multiple methods for ResNeXt-101-FPN are based on this t-car code ![微信截图_20240306160129](https://private-user-images.githubusercontent.com/85209124/310426428-c68fc843-1df4-40aa-af81-7234ac484fbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Nzk4OTcsIm5iZiI6MTcwOTc3OTU5NywicGF0aCI6Ii84NTIwOTEyNC8zMTA0MjY0MjgtYzY4ZmM4NDMtMWRmNC00MGFhLWFmODEtNzIzNGFjNDg0ZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAyNDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZTRlNGMxMmZhYTBhYzQzYWJmMGMxNTNkZTY3MTMzNDQwZmY5ZjM2MDM5YTE3ZjAyNzQzOGI5MGQyMzJiY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j_hgraWi4Eu_XPRF2oRZLitaRxmoXRcm-zk6JVPQgZA)
> > 
> > 
> > Yes, we infer all of these baseline methods based on our generated `zeroshot_triplet_new.pytorch` for fair comparision.
> 
> ![31313](https://private-user-images.githubusercontent.com/85209124/310754517-d79e5188-ad67-46c6-a2e6-b911168d78fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTExNzUsIm5iZiI6MTcwOTg5MDg3NSwicGF0aCI6Ii84NTIwOTEyNC8zMTA3NTQ1MTctZDc5ZTUxODgtYWQ2Ny00NmM2LWEyZTYtYjkxMTE2OGQ3OGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA5NDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMDlkNGM2MDAxMjM5Y2JmYmNmZGM3MTAzZWUzNjJkN2NlYjUxYTM0MWQ4N2JkMGVlNjczNWQ2NDRjYmEyY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MzvyUb8L8oMgpb2xZD2Kk4MKSQW1xjgdjROvW-HVjQ4) Hello, the method implementation of the red line part in the figure is not in this link code


These models have their own repos (you can check their original papers). You can replace the `zeroshot_triplet.pytorch` in their repository with our `zeroshot_triplet_new.pytorch`, and use their released pre-training parameters for inference to obtain the results in our paper. As for UVTransE, we reproduced their method based on their paper and this part of the code is not released here.

**Comment by Lxy811** [comment]
> > > > Sorry to bother you again, but I also want to ask backbone B whether the experimental results of multiple methods for ResNeXt-101-FPN are based on this t-car code ![微信截图_20240306160129](https://private-user-images.githubusercontent.com/85209124/310426428-c68fc843-1df4-40aa-af81-7234ac484fbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Nzk4OTcsIm5iZiI6MTcwOTc3OTU5NywicGF0aCI6Ii84NTIwOTEyNC8zMTA0MjY0MjgtYzY4ZmM4NDMtMWRmNC00MGFhLWFmODEtNzIzNGFjNDg0ZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAyNDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZTRlNGMxMmZhYTBhYzQzYWJmMGMxNTNkZTY3MTMzNDQwZmY5ZjM2MDM5YTE3ZjAyNzQzOGI5MGQyMzJiY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j_hgraWi4Eu_XPRF2oRZLitaRxmoXRcm-zk6JVPQgZA)
> > > 
> > > 
> > > Yes, we infer all of these baseline methods based on our generated `zeroshot_triplet_new.pytorch` for fair comparision.
> > 
> > 
> > ![31313](https://private-user-images.githubusercontent.com/85209124/310754517-d79e5188-ad67-46c6-a2e6-b911168d78fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTExNzUsIm5iZiI6MTcwOTg5MDg3NSwicGF0aCI6Ii84NTIwOTEyNC8zMTA3NTQ1MTctZDc5ZTUxODgtYWQ2Ny00NmM2LWEyZTYtYjkxMTE2OGQ3OGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA5NDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMDlkNGM2MDAxMjM5Y2JmYmNmZGM3MTAzZWUzNjJkN2NlYjUxYTM0MWQ4N2JkMGVlNjczNWQ2NDRjYmEyY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MzvyUb8L8oMgpb2xZD2Kk4MKSQW1xjgdjROvW-HVjQ4) Hello, the method implementation of the red line part in the figure is not in this link code
> 
> These models have their own repos (you can check their original papers). You can replace the `zeroshot_triplet.pytorch` in their repository with our `zeroshot_triplet_new.pytorch`, and use their released pre-training parameters for inference to obtain the results in our paper. As for UVTransE, we reproduced their method based on their paper and this part of the code is not released here.

thank you very much.
