### ISSUE TITLE
zR@50/100

### ISSUE THREAD

**Issue by Lxy811** [jkli1998/T-CAR#8]
Hello, I want to learn about the calculation of this index zR@50/100, how to get this evaluation result, what is the meaning?
![Snipaste_2024-03-20_09-27-49](https://github.com/jkli1998/T-CAR/assets/85209124/301f049e-32b7-441c-b66f-8905291d1682)

**Comment by jkli1998** [comment]
You can check this page for more details: https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/master/METRICS.md#explanation-of-our-metrics

**Comment by Lxy811** [comment]
> You can check this page for more details: https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/master/METRICS.md#explanation-of-our-metrics

OK，thank you.
